# The URL the site will be built for
base_url = "https://sverma1210.github.io/personal-website/"
title = "Shweta Verma"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlighting.code = true
highlighting.theme = "catppuccin-mocha"


[slugify]
paths = "on"
taxonomies = "on"
anchors = "on"



[extra]
# Put all your custom variables here
avatar = "static/img/avatar.jpg"
favicon = "static/img/avatar.jpg"

contact_in_index = true

# Additional menu items
# `Name` is what it is displayed, `path` is the url
menu_items = [
   { path = "#contacts", name = "Contact" },
]

# Translation related extra
language_codes = [ "en" ]

enable_theme_switching = false

daisyui_theme_light = "retro"
daisyui_theme_dark = "retro"

themes = [
    { identifier = "retro", name = "Retro" },
    ]

[extra.social]
github = "https://github.com/sverma1210"
academic = "https://scholar.google.com/citations?hl=en&user=w11vyB8AAAAJ"
linkedin = "https://www.linkedin.com/in/sverma12/"
email = "me.shweta.sv12[at]gmail.com"

[extra.navbar]
links = [
    { url = "research", i18n_key = "research" },
    { url = "publications", i18n_key = "pubs" },
    #{ url = "about me", i18n_key = "about" },
]
