# The URL the site will be built for
base_url = "https://example.com"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = false

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

title = "Shweta Verma"

[translations]
Biography = "Biography"
Interests = "Interests"
Education = "Education"
toc = "Table of Contents"
Published = "Published"
Abstract = "Abstract"
volume = "volume"
number = "number"
pages = "pages"

# Various slugification strategies, see below for details
# Defaults to everything being a slug
[slugify]
paths = "on"
taxonomies = "on"
anchors = "on"

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola

[markdown.highlighting]
theme = "catppuccin-mocha"

[extra]
favicon = "static/img/avatar.jpg"
version = "1.0.1"
avatar = "static/img/avatar.jpg"


# Enter your email
email = "me.shweta.sv12[at]gmail.com"

contact_in_index = true

# Additional menu items
# `Name` is what it is displayed, `path` is the url
menu_items = [
   { path = "#contacts", name = "Contact" },
]

# Translation related extra
language_codes = [ "en", "fr" ]

[extra.fr]
contact_in_index = false
menu_items = [
  # { path = "#contacts_fr", name = "Contact" },
]

# Your translations
[languages.fr]
title = "Kodama"

[languages.fr.translations]
Biography = "Bio"
Interests = "Interêts"
Education = "Formation"
Published = "Publication"
Abstract = "Résumé"




#avatar_icons = "static/img/avatar.jpg"
